# Generated by Django 5.0.9 on 2026-01-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('super_user', 'Super User')], default='user', max_length=32),
        ),
    ]
