# Generated by Django 5.0.9 on 2026-01-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(),
        ),
    ]
