# Generated by Django 5.0.9 on 2026-01-12 18:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationTask',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('product_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='List of product IDs associated with this task', size=None)),
                ('custom_prompt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='api.appuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='api.imagegenerationtask')),
            ],
        ),
    ]
