services:
  - type: web
    name: wearlytic-analytics
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: MONGODB_URI
        sync: false 