name: Trial Deploy Run on VPS (vps.theheadlyn.com)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Phase 1: Setup SSH + Cloudflared
      - name: Setup SSH and Cloudflared
        run: |
          sudo apt update
          sudo apt install -y sshpass
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
          mkdir -p ~/.ssh
          echo "
          Host vps
            HostName ${{ secrets.VPS_HOST }}
            User ${{ secrets.VPS_USER }}
            StrictHostKeyChecking no
            ProxyCommand cloudflared access ssh --hostname %h
          " > ~/.ssh/config

      # Phase 2: Connect to VPS
      - name: Connect to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" \
          ssh vps "echo Connected to VPS successfully"

      # Phase 3: Log GitHub Action
      - name: Log Deployment Action
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" \
          ssh vps "
            pwd
            cd logs &&
            echo '========== ACTION RUN ==========' >> actions.log &&
            echo 'GitHub Action Triggered' >> actions.log &&
            date >> .log &&
            echo '' >> actions.log
          "
      
      #Phase 4: Creating New Docker images
      - name:
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" \
          ssh vps "
            cd apps/Wearlytic &&
            git pull &&
            docker compose up -d scraping-agent data-ingestor --build --remove-orphans
          "